// <auto-generated />
using System;
using LibraryManagementAPI.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LibraryManagementAPI.Migrations
{
    [DbContext(typeof(LibraryDbContext))]
    [Migration("20251205040807_AddCartTableToDatabase")]
    partial class AddCartTableToDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AuthorBook", b =>
                {
                    b.Property<Guid>("AuthorsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BooksId")
                        .HasColumnType("uuid");

                    b.HasKey("AuthorsId", "BooksId");

                    b.HasIndex("BooksId");

                    b.ToTable("AuthorBook");
                });

            modelBuilder.Entity("BookBookCategory", b =>
                {
                    b.Property<Guid>("BookCategoriesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BooksId")
                        .HasColumnType("uuid");

                    b.HasKey("BookCategoriesId", "BooksId");

                    b.HasIndex("BooksId");

                    b.ToTable("BookCategoryMap", (string)null);
                });

            modelBuilder.Entity("LibraryManagementAPI.Entities.Account", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("isActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("lastLogin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("passwordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("role")
                        .HasColumnType("integer");

                    b.Property<string>("userName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            id = new Guid("a0000000-0000-0000-0000-000000000001"),
                            createdAt = new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            isActive = true,
                            lastLogin = new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            passwordHash = "hashed_password",
                            role = 0,
                            userName = "admin"
                        },
                        new
                        {
                            id = new Guid("a0000000-0000-0000-0000-000000000011"),
                            createdAt = new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            isActive = true,
                            lastLogin = new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            passwordHash = "hashed_password1",
                            role = 0,
                            userName = "admin"
                        },
                        new
                        {
                            id = new Guid("b0000000-0000-0000-0000-000000000002"),
                            createdAt = new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            isActive = true,
                            lastLogin = new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            passwordHash = "hashed_password",
                            role = 1,
                            userName = "staff"
                        },
                        new
                        {
                            id = new Guid("c0000000-0000-0000-0000-000000000003"),
                            createdAt = new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            isActive = true,
                            lastLogin = new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            passwordHash = "hashed_password",
                            role = 2,
                            userName = "member"
                        });
                });

            modelBuilder.Entity("LibraryManagementAPI.Entities.Author", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BriefDescription")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("YearOfBirth")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Authors");
                });

            modelBuilder.Entity("LibraryManagementAPI.Entities.BaseInfo", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("email")
                        .HasColumnType("text");

                    b.Property<string>("fullName")
                        .HasColumnType("text");

                    b.Property<Guid>("loginId")
                        .HasColumnType("uuid");

                    b.Property<string>("phoneNumber")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("loginId")
                        .IsUnique();

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("LibraryManagementAPI.Entities.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImgUrl")
                        .HasColumnType("text");

                    b.Property<int>("PublicationYear")
                        .HasColumnType("integer");

                    b.Property<Guid?>("PublisherId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PublisherId");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("LibraryManagementAPI.Entities.BookCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("BookCategories");
                });

            modelBuilder.Entity("LibraryManagementAPI.Entities.BookCopy", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("bookId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("bookImportDetailId")
                        .HasColumnType("uuid");

                    b.Property<int>("status")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("bookId");

                    b.ToTable("BookCopies");

                    b.HasData(
                        new
                        {
                            id = new Guid("00989681-0000-0000-0000-000000000009"),
                            bookId = new Guid("019a1a78-7b67-7f6c-9d63-f2d13554c669"),
                            bookImportDetailId = new Guid("f0000000-0000-0000-0000-000000000007"),
                            status = 0
                        },
                        new
                        {
                            id = new Guid("00989682-0000-0000-0000-000000000009"),
                            bookId = new Guid("019a1a78-7b67-7f6c-9d63-f2d13554c669"),
                            bookImportDetailId = new Guid("f0000000-0000-0000-0000-000000000007"),
                            status = 0
                        },
                        new
                        {
                            id = new Guid("00989683-0000-0000-0000-000000000009"),
                            bookId = new Guid("019a1a78-7b67-7f6c-9d63-f2d13554c669"),
                            bookImportDetailId = new Guid("f0000000-0000-0000-0000-000000000007"),
                            status = 0
                        },
                        new
                        {
                            id = new Guid("00989684-0000-0000-0000-000000000009"),
                            bookId = new Guid("019a1a78-7b67-7f6c-9d63-f2d13554c669"),
                            bookImportDetailId = new Guid("f0000000-0000-0000-0000-000000000007"),
                            status = 0
                        },
                        new
                        {
                            id = new Guid("00989685-0000-0000-0000-000000000009"),
                            bookId = new Guid("019a1a78-7b67-7f6c-9d63-f2d13554c669"),
                            bookImportDetailId = new Guid("f0000000-0000-0000-0000-000000000007"),
                            status = 0
                        },
                        new
                        {
                            id = new Guid("00989686-0000-0000-0000-000000000009"),
                            bookId = new Guid("019a1a78-7b67-7f6c-9d63-f2d13554c669"),
                            bookImportDetailId = new Guid("f0000000-0000-0000-0000-000000000007"),
                            status = 0
                        },
                        new
                        {
                            id = new Guid("00989687-0000-0000-0000-000000000009"),
                            bookId = new Guid("019a1a78-7b67-7f6c-9d63-f2d13554c669"),
                            bookImportDetailId = new Guid("f0000000-0000-0000-0000-000000000007"),
                            status = 0
                        },
                        new
                        {
                            id = new Guid("00989688-0000-0000-0000-000000000009"),
                            bookId = new Guid("019a1a78-7b67-7f6c-9d63-f2d13554c669"),
                            bookImportDetailId = new Guid("f0000000-0000-0000-0000-000000000007"),
                            status = 0
                        },
                        new
                        {
                            id = new Guid("00989689-0000-0000-0000-000000000009"),
                            bookId = new Guid("019a1a78-7b67-7f6c-9d63-f2d13554c669"),
                            bookImportDetailId = new Guid("f0000000-0000-0000-0000-000000000007"),
                            status = 0
                        },
                        new
                        {
                            id = new Guid("0098968a-0000-0000-0000-000000000009"),
                            bookId = new Guid("019a1a78-7b67-7f6c-9d63-f2d13554c669"),
                            bookImportDetailId = new Guid("f0000000-0000-0000-0000-000000000007"),
                            status = 0
                        });
                });

            modelBuilder.Entity("LibraryManagementAPI.Entities.BookImport", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("importDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("note")
                        .HasColumnType("text");

                    b.Property<Guid>("staffId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("supplierId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("totalAmount")
                        .HasColumnType("numeric");

                    b.HasKey("id");

                    b.HasIndex("staffId");

                    b.HasIndex("supplierId");

                    b.ToTable("BookImports");

                    b.HasData(
                        new
                        {
                            id = new Guid("e0000000-0000-0000-0000-000000000005"),
                            importDate = new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            note = "First Import",
                            staffId = new Guid("019aa216-657c-7b6d-abd5-6db1b06317ee"),
                            supplierId = new Guid("d0000000-0000-0000-0000-000000000004"),
                            totalAmount = 0m
                        },
                        new
                        {
                            id = new Guid("e0000000-0000-0000-0000-000000000006"),
                            importDate = new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            note = "Second Import",
                            staffId = new Guid("019aa216-657c-7b6d-abd5-6db1b06317ee"),
                            supplierId = new Guid("d0000000-0000-0000-0000-000000000004"),
                            totalAmount = 0m
                        });
                });

            modelBuilder.Entity("LibraryManagementAPI.Entities.BookImportDetail", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("bookId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("bookImportId")
                        .HasColumnType("uuid");

                    b.Property<int>("quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("unitPrice")
                        .HasColumnType("numeric");

                    b.HasKey("id");

                    b.HasIndex("bookId");

                    b.HasIndex("bookImportId");

                    b.ToTable("BookImportDetails");

                    b.HasData(
                        new
                        {
                            id = new Guid("f0000000-0000-0000-0000-000000000007"),
                            bookId = new Guid("019a1a78-7b67-7f6c-9d63-f2d13554c669"),
                            bookImportId = new Guid("e0000000-0000-0000-0000-000000000005"),
                            quantity = 10,
                            unitPrice = 100m
                        },
                        new
                        {
                            id = new Guid("f0000000-0000-0000-0000-000000000008"),
                            bookId = new Guid("019a1a78-7b67-7f6c-9d63-f2d13554c669"),
                            bookImportId = new Guid("e0000000-0000-0000-0000-000000000006"),
                            quantity = 5,
                            unitPrice = 200m
                        });
                });

            modelBuilder.Entity("LibraryManagementAPI.Entities.BookTransaction", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("borrowDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("copyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("dueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("memberId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("returnDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("staffId")
                        .HasColumnType("uuid");

                    b.Property<int>("status")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("copyId");

                    b.HasIndex("memberId");

                    b.HasIndex("staffId");

                    b.ToTable("BookTransactions");
                });

            modelBuilder.Entity("LibraryManagementAPI.Entities.BorrowRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("QrCode")
                        .HasColumnType("text");

                    b.Property<Guid?>("StaffId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("StaffId");

                    b.ToTable("BorrowRequests");
                });

            modelBuilder.Entity("LibraryManagementAPI.Entities.BorrowRequestItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BookCopyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BorrowRequestId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("BookCopyId");

                    b.HasIndex("BookId");

                    b.HasIndex("BorrowRequestId");

                    b.ToTable("BorrowRequestItems");
                });

            modelBuilder.Entity("LibraryManagementAPI.Entities.Cart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("LibraryManagementAPI.Entities.CartItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CartId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("CartId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("LibraryManagementAPI.Entities.Publisher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Publishers");
                });

            modelBuilder.Entity("LibraryManagementAPI.Entities.Supplier", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("address")
                        .HasColumnType("text");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("phoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Supplier");

                    b.HasData(
                        new
                        {
                            id = new Guid("d0000000-0000-0000-0000-000000000004"),
                            address = "",
                            email = "",
                            name = "Default Supplier",
                            phoneNumber = ""
                        });
                });

            modelBuilder.Entity("LibraryManagementAPI.Entities.AdminInfo", b =>
                {
                    b.HasBaseType("LibraryManagementAPI.Entities.BaseInfo");

                    b.ToTable("AdminInfos");

                    b.HasData(
                        new
                        {
                            id = new Guid("a0000000-0000-0000-0000-000000000011"),
                            email = "admin@gmail.com",
                            fullName = "Admin",
                            loginId = new Guid("a0000000-0000-0000-0000-000000000001"),
                            phoneNumber = "0321547895"
                        },
                        new
                        {
                            id = new Guid("a0000000-0000-0000-0000-000000000111"),
                            email = "admin@gmail.com",
                            fullName = "Admin",
                            loginId = new Guid("a0000000-0000-0000-0000-000000000011"),
                            phoneNumber = "0321547895"
                        });
                });

            modelBuilder.Entity("LibraryManagementAPI.Entities.MemberInfo", b =>
                {
                    b.HasBaseType("LibraryManagementAPI.Entities.BaseInfo");

                    b.Property<string>("address")
                        .HasColumnType("text");

                    b.Property<string>("imageUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("joinDate")
                        .HasColumnType("timestamp with time zone");

                    b.ToTable("MemberInfos");

                    b.HasData(
                        new
                        {
                            id = new Guid("c0000000-0000-0000-0000-000000000033"),
                            email = "member@gmail.com",
                            fullName = "Member",
                            loginId = new Guid("c0000000-0000-0000-0000-000000000003"),
                            phoneNumber = "0321547897",
                            address = "123 Main St",
                            imageUrl = "http://example.com/image.jpg",
                            joinDate = new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("LibraryManagementAPI.Entities.StaffInfo", b =>
                {
                    b.HasBaseType("LibraryManagementAPI.Entities.BaseInfo");

                    b.Property<DateTime>("hireDate")
                        .HasColumnType("timestamp with time zone");

                    b.ToTable("StaffInfos");

                    b.HasData(
                        new
                        {
                            id = new Guid("b0000000-0000-0000-0000-000000000022"),
                            email = "staff@gmail.com",
                            fullName = "Staff",
                            loginId = new Guid("b0000000-0000-0000-0000-000000000002"),
                            phoneNumber = "0321547896",
                            hireDate = new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("AuthorBook", b =>
                {
                    b.HasOne("LibraryManagementAPI.Entities.Author", null)
                        .WithMany()
                        .HasForeignKey("AuthorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryManagementAPI.Entities.Book", null)
                        .WithMany()
                        .HasForeignKey("BooksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BookBookCategory", b =>
                {
                    b.HasOne("LibraryManagementAPI.Entities.BookCategory", null)
                        .WithMany()
                        .HasForeignKey("BookCategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryManagementAPI.Entities.Book", null)
                        .WithMany()
                        .HasForeignKey("BooksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LibraryManagementAPI.Entities.BaseInfo", b =>
                {
                    b.HasOne("LibraryManagementAPI.Entities.Account", "account")
                        .WithOne("info")
                        .HasForeignKey("LibraryManagementAPI.Entities.BaseInfo", "loginId");

                    b.Navigation("account");
                });

            modelBuilder.Entity("LibraryManagementAPI.Entities.Book", b =>
                {
                    b.HasOne("LibraryManagementAPI.Entities.Publisher", "Publisher")
                        .WithMany("Books")
                        .HasForeignKey("PublisherId");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("LibraryManagementAPI.Entities.BookCopy", b =>
                {
                    b.HasOne("LibraryManagementAPI.Entities.Book", "book")
                        .WithMany()
                        .HasForeignKey("bookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("book");
                });

            modelBuilder.Entity("LibraryManagementAPI.Entities.BookImport", b =>
                {
                    b.HasOne("LibraryManagementAPI.Entities.StaffInfo", "staff")
                        .WithMany()
                        .HasForeignKey("staffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryManagementAPI.Entities.Supplier", "supplier")
                        .WithMany("bookImports")
                        .HasForeignKey("supplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("staff");

                    b.Navigation("supplier");
                });

            modelBuilder.Entity("LibraryManagementAPI.Entities.BookImportDetail", b =>
                {
                    b.HasOne("LibraryManagementAPI.Entities.Book", "book")
                        .WithMany()
                        .HasForeignKey("bookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryManagementAPI.Entities.BookImport", "bookImport")
                        .WithMany("bookImportDetails")
                        .HasForeignKey("bookImportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("book");

                    b.Navigation("bookImport");
                });

            modelBuilder.Entity("LibraryManagementAPI.Entities.BookTransaction", b =>
                {
                    b.HasOne("LibraryManagementAPI.Entities.BookCopy", "book")
                        .WithMany()
                        .HasForeignKey("copyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryManagementAPI.Entities.MemberInfo", "member")
                        .WithMany()
                        .HasForeignKey("memberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryManagementAPI.Entities.StaffInfo", "staff")
                        .WithMany()
                        .HasForeignKey("staffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("book");

                    b.Navigation("member");

                    b.Navigation("staff");
                });

            modelBuilder.Entity("LibraryManagementAPI.Entities.BorrowRequest", b =>
                {
                    b.HasOne("LibraryManagementAPI.Entities.MemberInfo", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryManagementAPI.Entities.StaffInfo", "Staff")
                        .WithMany()
                        .HasForeignKey("StaffId");

                    b.Navigation("Member");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("LibraryManagementAPI.Entities.BorrowRequestItem", b =>
                {
                    b.HasOne("LibraryManagementAPI.Entities.BookCopy", "BookCopy")
                        .WithMany()
                        .HasForeignKey("BookCopyId");

                    b.HasOne("LibraryManagementAPI.Entities.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryManagementAPI.Entities.BorrowRequest", "BorrowRequest")
                        .WithMany("Items")
                        .HasForeignKey("BorrowRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("BookCopy");

                    b.Navigation("BorrowRequest");
                });

            modelBuilder.Entity("LibraryManagementAPI.Entities.CartItem", b =>
                {
                    b.HasOne("LibraryManagementAPI.Entities.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LibraryManagementAPI.Entities.Cart", "Cart")
                        .WithMany("Items")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Cart");
                });

            modelBuilder.Entity("LibraryManagementAPI.Entities.Account", b =>
                {
                    b.Navigation("info");
                });

            modelBuilder.Entity("LibraryManagementAPI.Entities.BookImport", b =>
                {
                    b.Navigation("bookImportDetails");
                });

            modelBuilder.Entity("LibraryManagementAPI.Entities.BorrowRequest", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("LibraryManagementAPI.Entities.Cart", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("LibraryManagementAPI.Entities.Publisher", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("LibraryManagementAPI.Entities.Supplier", b =>
                {
                    b.Navigation("bookImports");
                });
#pragma warning restore 612, 618
        }
    }
}
