name: deploy .NET

on:
    push:
        branches: ["demo-cicd"]

jobs:
    deploy:
        runs-on: ubuntu-latest
        env:
            IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
            CONTAINER_NAME: ${{ secrets.CONTAINER_NAME }}

        steps:
        - name: checkout
          uses: actions/checkout@v4
        
        - name: Log in to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Build and push docker image
          run: |
            docker build -t $IMAGE_NAME .
            docker push $IMAGE_NAME
        
        - name: Deploy
          uses: appleboy/ssh-action@v1.2.0
          with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USER }}
            key: ${{ secrets.SSH_KEY }}
            script: |
                docker pull $IMAGE_NAME
                docker stop $CONTAINER_NAME || true
                docker rm $CONTAINER_NAME || true
                docker run -d --name $CONTAINER_NAME -p 8080:8080 $IMAGE_NAME
        

        